### ISSUE TITLE
fix: secret property 공개  🚨🚨

### ISSUE THREAD

**Issue by anjm1020** [UnivCert/univcert-api#13]
## Description
라이브러리 코드를 살펴보던 중 mail, rds관련 정보들이
resource 패키지 하위 파일에 그대로 노출되어 있는 것을 확인하였습니다.

## Request
해당 프로퍼티는 가리는게 좋지 않을까 제안드려 봅니다.

**Comment by in-seo** [comment]
@anjm1020 좋은 지적 감사합니다.  해당 키 값은 전부 deprecate 된 정보라서 기록에 남겨도 무방하다고 판단했습니다 !
